### ISSUE TITLE
Question about uv_queue_work vs uv_async_send

### ISSUE THREAD

**Issue by sulliwane** [freezer333/streaming-worker#1]
Hi Scott,

after reading your book, I have a question that comes to my mind:
# Problem

I have to wrap a C++ dynamic library (.so), this lib is actually connected to a remote server that will remotely and repeatedly send data to my lib by calling the lib virtual functions with new data as parameter (a bit like RPC).

I need to write these virtual functions, implemented by the c++ lib.

For simplicity, let's say there is only one c++ virtual function:

``` cpp
void c++OnData(data myData)
```

From my JS code, let's say I register a unique callback that needs to get call everytime there is new data: 

``` javascript
obj.registerCallback(function jsOnData(myData) {
   console.log(myData);
})
```

From my understanding, there is kind of **two ways** to wake up the `uv_default_loop()` from my lib virtual function, which then will be able to inject the data into v8.
# First option - uv_queue_work()

Example:

``` cpp
Nan::Callback*  myRegisteredCallback;

void _on_async(uv_work_t * work){
    //do nothing
}

void _on_completed(uv_work_t * work,int){
  data* myData = static_cast<data*>(work->data);
  myRegisteredCallback->call(myData);
}

virtual void mylib::c++OnData(data myData) {
    uv_queue_work(uv_default_loop(), &field->work, _on_async, _on_completed);
}
```
# Second option - uv_async_send()

Note: Not written: To avoid loosing data, this second option will need to implement a queue, so the `_on_complete()` function will iterate over the queue and call one by one `myRegisteredCallback->call(myData);` (like in your streaming-worker example).

Example:

``` cpp
Nan::Callback*  myRegisteredCallback;
uv_async_t async;
uv_async_init(uv_default_loop(), &async, _on_completed);

void _on_completed(uv_async_t* handle) {
  myRegisteredCallback->call(myData);
}

virtual void mylib::c++OnData(data myData) {
  uv_async_send(&async);
}
```

Do I understand correctly these options? If yes, Here is my question:

What is the advantage of the second option (similar to **Nan：：AsyncProgressWorker**) over the simpler N°1 option (similar to **Nan::asyncWorker**) ? 

I feel like **Option 1** will be calling `uv_queue_work()` a lot, to get access to the **uv_default_loop()**, whereas **Option 2** will accumulate the data and call less often the **uv_default_loop()**. But I also have the feeling the fastest way to get my data into v8 would be with **option 1**...

Many thanks for your help :)

**Comment by sulliwane** [comment]
Hi Scott, any idea on this one? Thanks

**Comment by freezer333** [comment]
Hi - I'm away on vacation right now and haven't gotten a chance to dive
into this yet. My initial take is that performance would be the similar
overall - but I'd have to look into your option 1 more closely.

**Comment by sulliwane** [comment]
OK. Many thanks for your answer. I'll post when I'll have tried both solutions.
(Totally forgot it's holiday time, sorry!)

**Comment by freezer333** [comment]
After looking at this more closely - I don't think Option 1 is the approach
I'd take.  You are essentially starting up (albeit from a thread pool) a
new worker thread - to do nothing - only to get the completion callback to
fire (where you actually call your callback).  I'm not sure how much of a
performance penalty you'd end up having there - but it seems to me like
Option 2 (where you follow the example of Nan's AsyncProgressWorker and
streaming-worker would be the more standard approach.

**Comment by sulliwane** [comment]
Ok! Thank you for your answer. 

So I'm trying to implement **Option 2**, using parts of your streaming-worker SDK.

**To recall my Goal**: I have a **Lib** (a lib.so) that makes a connection to a remote server, which server will call every second some of the lib.so functions with some data (similar to a RPC call). **I want to make these data showing up in javascript!**

My Worker Class inherit from the **Lib** (and implement its virtual functions, which are called every second with some data), and also inherit from **Nan::AsyncProgressWorker** (as in your example).

However, the threading management in the **lib.so** is hidden from me, I just know that **it's running indefinitely** once it's connected to the remote server. SO differing from your example, I don't have to queue the worker like this:

``` cpp
// start the worker
AsyncQueueWorker(obj->_worker);
```

As I don't need to queue the worker, my Worker Class member `void Execute(const ExecutionProgress& execProgress);` is never called. Instead, I will call `writeToNode(execProgress, data);` from my lib virtual function:

``` cpp
void MyWorker::MyLibVirtualFunctionCalledEverySecond(data)
{
  writeToNode(execProgress, data);  <--- Error, missing execProgress
}
```

My problem is that I don't have execProgress variable, as this is **AsyncProgressWorker** who take care to initialize it and give it to `void Execute(const ExecutionProgress& execProgress)`. So I tried this:

``` cpp
void MyWorker::MyLibVirtualFunctionCalledEverySecond(data)
{
  ExecutionProgress execProgress(this);   <--- try to initialize execProgress by calling its constructor
  writeToNode(execProgress, data);
}
```

But I get an error, because `ExecutionProgress()` constructor is a private member (as you can see[ HERE in nan.h](https://github.com/nodejs/nan/blob/7dda24df9b85438974b2e4c10a2fc1b9c66dd306/nan.h#L1618)) or below copy:

``` cpp
 class ExecutionProgress {
    friend class AsyncProgressWorkerBase;
   public:
    void Signal() const {
        uv_async_send(that_->async);
    }

    void Send(const T* data, size_t size) const {
        that_->SendProgress_(data, size);
    }

   private:
    explicit ExecutionProgress(AsyncProgressWorkerBase *that) : that_(that) {}
    NAN_DISALLOW_ASSIGN_COPY_MOVE(ExecutionProgress)
    AsyncProgressWorkerBase* const that_;
};
```

If I make the  `ExecutionProgress()` constructor public, it seems to work fine. But modifying **nan.h** is not a valid/durable solution I guess.

May I ask you some help/advice on this problem? What is the best option to instantiate the  `ExecutionProgress` Class, from my Worker Class, so I can call your method **writeToNode(execProgress, data);** with the correct **execProgress** parameter?

The solution may be obvious, but I come from javascript, and my C++ skills are very limited... :(

Cheers :)

**Comment by freezer333** [comment]
I think you actually _should_ queue the worker.  It sounds like you have a
more complex setup than the streaming worker examples are focused on,
because you have a three parts:

1)  Node.js event loop
2)  Your "worker"
3)  A remote process that initiates the execution of a callbacks on your
worker (the virtual functions).

I think the way I'd handle it is I'd have the virtual functions (callbacks)
queue the data into a structure in your worker.  Then in your worker's
Execute function, just poll the queue and ship the data off to Node (since
you have the progress object).  You'll need to synchronize access to the
queue between the worker thread and the RPC thread that is invoking  your
virtual functions.
